# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: CC-BY-NC-4.0

log: false  # set to False to avoid the logging

wandb_arg:
  _target_: pytorch_lightning.loggers.WandbLogger
  project: ${train.model_name}
  name: ${train.model_name}
  save_dir: ./
  log_model: True
  mode: 'offline'

watch:
  log: 'all'
  log_freq: 100